In [40]:
import torch
import torch.nn as nn

In [41]:
x = torch.FloatTensor(4) # input
W = torch.FloatTensor(4, 3) # weight
b = torch.FloatTensor(3) # bias  

def linearfunction(x, W, b):
    y = torch.matmul(W, x) + b
    return y

In [42]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.W = torch.FloatTensor(4, 3) # weight
        self.b = torch.FloatTensor(3) # bias

    def forward(self, x): # calculation of the output
        #|x| = (input_dim)
        #|y| = (input_dim) * (input_dim, output_dim) + (output_dim)
        #    = (output_dim)
        y = torch.matmul(x, self.W) + self.b
        return y

In [43]:
x = torch.FloatTensor(4) # input
mylinear = NeuralNetwork()
y = mylinear(x) # mylinear.forward(x)와 동일
print(y, y.size())

tensor([0., 0., 0.]) torch.Size([3])


In [44]:
class NeuralNetwork(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.W = torch.FloatTensor(input_dim, output_dim)
        self.b = torch.FloatTensor(output_dim)
        

    def forward(self, x):
        #|x| = (input_dim)
        #|y| = (input_dim) * (input_dim, output_dim) + (output_dim)
        #    = (output_dim)
        y = torch.matmul(x, self.W) + self.b
        return y

In [45]:
x = torch.FloatTensor(5) # input
mylinear = NeuralNetwork(5, 3)
y = mylinear(x) # mylinear.forward(x)와 동일
print(y, y.size()) 

tensor([0., 0., 0.]) torch.Size([3])


In [46]:
class NeuralNetwork(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.W = nn.Parameter(torch.FloatTensor(input_dim, output_dim)) # nn.Parameter를 사용하면 학습 가능한 parameter로 등록
        self.b = nn.Parameter(torch.FloatTensor(output_dim)) # nn.Parameter를 사용하면 학습 가능한 parameter로 등록
        
    def forward(self, x):
        #|x| = (input_dim)
        #|y| = (input_dim) * (input_dim, output_dim) + (output_dim)
        #    = (output_dim)
        y = torch.matmul(x, self.W) + self.b
        return y
    

In [47]:
x = torch.FloatTensor(4) # input
mylinear = NeuralNetwork(4, 3)
y = mylinear(x) # mylinear.forward(x)와 동일
print(y, y.size())
for param in mylinear.parameters():
    print(param) # requries_grad=True 에 따라 paremeter를 업데이트 할지 말지 결정
                # vaildation set이나 test set에서는 requires_grad=False로 설정 (말그대로 테스트를 위한 것이기 때문에 업데이트 하지 않는다)

tensor([0., 0., 0.], grad_fn=<AddBackward0>) torch.Size([3])
Parameter containing:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], requires_grad=True)
Parameter containing:
tensor([0., 0., 0.], requires_grad=True)


In [48]:
mylinear = nn.Linear(4, 3) # nn.Linear는 위에서 정의한 NeuralNetwork과 동일한 기능을 한다
y = mylinear(x)
print(y, y.size())

for param in mylinear.parameters():
    print(param) # nn.Linear는 내부적으로 nn.Parameter를 사용하기 때문에 parameter를 업데이트 할 수 있다
                # requires_grad=True로 학습 가능한 parameter로 등록되어 있다

tensor([-0.1558, -0.1228, -0.3506], grad_fn=<ViewBackward0>) torch.Size([3])
Parameter containing:
tensor([[-0.1992,  0.0773, -0.3740, -0.0443],
        [-0.4586, -0.2748,  0.3761, -0.4215],
        [ 0.2162,  0.4703, -0.1746, -0.3870]], requires_grad=True)
Parameter containing:
tensor([-0.1558, -0.1228, -0.3506], requires_grad=True)


In [ ]:
# 하나의 모듈에 여거 모듈을 포함시킬 수 있다

class NeuralNetwork(nn.Module):
  
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.linear = nn.Linear(input_dim, output_dim)

    def forward(self, x):
        #|x| = (input_dim)
        #|y| = (input_dim) * (input_dim, output_dim) + (output_dim)
        #    = (output_dim)
        y= self.linear(x)
        return y
