In [46]:
import torch
import torch.nn as nn
import torch.nn.functional as F

data1 = torch.randn(3,4)
print(data1)
indices = torch.tensor([1,2]) # 1,2번째 행,열을 가져옴
print(indices)
print(torch.index_select(data1, 0, indices)) # 0 축을 기준으로 1,2번째 행을 가져옴
print(torch.index_select(data1, 1, indices)) # 1 축을 기준으로 1,2번째 열을 가져옴


tensor([[-0.1233, -0.7327,  0.9121, -0.0747],
        [ 1.1119, -0.7013, -2.3540, -1.3027],
        [ 0.7007,  0.9611, -0.4342,  0.3471]])
tensor([1, 2])
tensor([[ 1.1119, -0.7013, -2.3540, -1.3027],
        [ 0.7007,  0.9611, -0.4342,  0.3471]])
tensor([[-0.7327,  0.9121],
        [-0.7013, -2.3540],
        [ 0.9611, -0.4342]])


In [47]:
x = torch.ones(5000,10) # 5000개의 데이터, 10개의 특징
y = torch.zeros(5000,1) # 5000개의 데이터에 대한 예측값

learning_rate = 0.01
nb_epochs = 1000
mini_batch_size = 256 

In [48]:
input_dim = x.size(-1) # 10
output_dim = y.size(-1) # 1

model = nn.Sequential(
    nn.Linear(input_dim, 10),
    nn.LeakyReLU(0.1),
    nn.Linear(10, 8),
    nn.LeakyReLU(0.1),
    nn.Linear(8, 6),
    nn.LeakyReLU(0.1),
    nn.Linear(6, output_dim)
)

loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [49]:
for index in range(nb_epochs):

    indices = torch.randperm(x.size(0)) # 5000개의 데이터에 대한 인덱스를 랜덤하게 섞음
    x_batch_list = torch.index_select(x, 0, index=indices)
    y_batch_list = torch.index_select(y, 0, index=indices)
    x_batch_list = x_batch_list.split(mini_batch_size, dim=0) # mini_batch 생성
    y_batch_list = y_batch_list.split(mini_batch_size, dim=0) # mini_batch 생성
    
    for x_minibatch, y_minibatch in zip(x_batch_list, y_batch_list):
        y_pred = model(x_minibatch)
        loss = loss_fn(y_pred, y_minibatch)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

print(loss)
for param in model.parameters():
    print(param)

tensor(1.3553e-16, grad_fn=<MseLossBackward0>)
Parameter containing:
tensor([[-0.2679, -0.0344, -0.2605,  0.0918,  0.0302,  0.0214, -0.3016, -0.1171,
         -0.2156,  0.0351],
        [ 0.1124,  0.1762, -0.3135,  0.1598,  0.0177,  0.0204,  0.1546, -0.2700,
          0.1810, -0.1491],
        [ 0.0910,  0.0493,  0.0680,  0.3021, -0.0225, -0.2828, -0.1399, -0.0623,
          0.2018,  0.2156],
        [ 0.2562,  0.1169, -0.2756,  0.1799,  0.0894,  0.0494,  0.1497,  0.2411,
         -0.0648,  0.2172],
        [-0.0776, -0.2279, -0.2630,  0.0023, -0.0159,  0.2911, -0.0461, -0.1016,
         -0.0783,  0.3055],
        [-0.1738,  0.2886, -0.0949, -0.2071, -0.2162,  0.1225, -0.0041, -0.0071,
         -0.2747,  0.1396],
        [ 0.2406, -0.1152, -0.0742, -0.1968, -0.1110,  0.2823,  0.2306, -0.0756,
         -0.0875,  0.0723],
        [-0.2657,  0.1052, -0.1438, -0.3151, -0.2335, -0.2758,  0.1613, -0.2723,
         -0.1265, -0.2902],
        [ 0.1365, -0.1283, -0.2009, -0.1143, -0.0081, -0.20