In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

data1 = torch.randn(3,4)
print(data1)
indices = torch.tensor([1,2]) # 1,2번째 행,열을 가져옴
print(indices)
print(torch.index_select(data1, 0, indices)) # 0 축을 기준으로 1,2번째 행을 가져옴
print(torch.index_select(data1, 1, indices)) # 1 축을 기준으로 1,2번째 열을 가져옴


tensor([[ 0.2051, -0.8416,  0.5813,  0.3569],
        [-1.9076,  0.5036,  0.4022, -0.7124],
        [ 0.1171,  0.3482, -1.6894, -0.4675]])
tensor([1, 2])
tensor([[-1.9076,  0.5036,  0.4022, -0.7124],
        [ 0.1171,  0.3482, -1.6894, -0.4675]])
tensor([[-0.8416,  0.5813],
        [ 0.5036,  0.4022],
        [ 0.3482, -1.6894]])


In [ ]:
x = torch.ones(5000,10)
