In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

x = torch.ones(4)
y = torch.zeros(3)

input_dim = x.size(0)
output_dim = y.size(0)

model = nn.Sequential(
    nn.Linear(input_dim, 10),
    nn.LeakyReLU(0.1),
    nn.Linear(10, 10),
    nn.LeakyReLU(0.1),
    nn.Linear(10, 10),
    nn.LeakyReLU(0.1),
    nn.Linear(10, output_dim)
)

In [3]:
loss_fn = nn.MSELoss()
learning_rate = 0.01
nb_epochs = 1000
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(nb_epochs + 1):
    
    y_pred = model(x)
    loss = loss_fn(y_pred, y)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print(loss)
for param in model.parameters():
    print(param)

tensor(1.2978e-11, grad_fn=<MseLossBackward0>)
Parameter containing:
tensor([[ 0.4737,  0.0873, -0.2370,  0.3222],
        [ 0.4164,  0.1948, -0.4418,  0.0740],
        [-0.0808,  0.4454, -0.0956, -0.3349],
        [-0.2584, -0.1267, -0.0460,  0.3554],
        [-0.0010,  0.2491,  0.2936,  0.3873],
        [ 0.0367, -0.0138, -0.3862, -0.1776],
        [-0.3490, -0.3439, -0.1575, -0.2580],
        [ 0.2041,  0.0550, -0.1992,  0.1387],
        [ 0.0217, -0.4596,  0.1130,  0.4249],
        [ 0.3864,  0.1637, -0.0855,  0.0050]], requires_grad=True)
Parameter containing:
tensor([ 0.3832,  0.3146, -0.2049, -0.1923, -0.1195, -0.0007, -0.1644, -0.1917,
         0.0648, -0.0356], requires_grad=True)
Parameter containing:
tensor([[-0.2918,  0.2579, -0.3081,  0.2934, -0.1290, -0.0646,  0.2533, -0.0944,
          0.0559, -0.0793],
        [ 0.2042, -0.1175, -0.1943, -0.1885,  0.2087, -0.2251, -0.2694,  0.1077,
          0.0926,  0.2933],
        [-0.0209, -0.1829,  0.0558,  0.2640, -0.3005, -0.0754