In [3]:
# 다층 레이어 구현
# input layer -> hidden layer -> output layer 순으로 구성

import torch
import torch.nn as nn

class LinearRegressionModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.linear1 = nn.Linear(input_dim, 10)
        self.linear2 = nn.Linear(10, 10) 
        self.linear3 = nn.Linear(10, 10)
        self.linear4 = nn.Linear(10, output_dim) 
        self.activation = nn.LeakyReLU(0.1)

    def forward(self, x):
        hidden = self.activation(self.linear1(x))
        hidden = self.activation(self.linear2(hidden))
        hidden = self.activation(self.linear3(hidden))
        y = self.linear4(hidden) # 마지막 출력에는 activation function을 사용하지 않음
        return y

In [4]:
x = torch.ones(4)
y = torch.zeros(3)
model = LinearRegressionModel(4, 3)
loss_fn = nn.MSELoss()

In [5]:
learning_rate = 0.01
nb_epochs = 1000
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(nb_epochs + 1):
    y_pred = model(x)
    loss = loss_fn(y_pred, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print(loss)
for param in model.parameters():
    print(param)

tensor(6.4008e-10, grad_fn=<MseLossBackward0>)
Parameter containing:
tensor([[ 0.1745,  0.3462,  0.0218, -0.0936],
        [-0.0153,  0.2503, -0.0496,  0.0696],
        [-0.1459,  0.0704, -0.2363, -0.3638],
        [ 0.4800,  0.3918,  0.1549, -0.2321],
        [-0.0454, -0.2194, -0.1364,  0.0475],
        [-0.4809,  0.0362, -0.0198,  0.1904],
        [ 0.4787, -0.4818,  0.4565,  0.0256],
        [-0.2231,  0.4883, -0.4384,  0.2023],
        [ 0.3695,  0.3422, -0.1641, -0.2309],
        [ 0.2564, -0.2759, -0.0363, -0.0125]], requires_grad=True)
Parameter containing:
tensor([ 0.4034, -0.4755,  0.4147,  0.2092, -0.3845,  0.3379,  0.1719, -0.1932,
        -0.0182, -0.1498], requires_grad=True)
Parameter containing:
tensor([[-0.2184, -0.0227, -0.0215,  0.1802, -0.1862,  0.1847, -0.2704,  0.2748,
          0.3102,  0.2107],
        [-0.1935,  0.1494,  0.1637, -0.1262,  0.2294, -0.0867,  0.0662,  0.2949,
         -0.1954,  0.0146],
        [-0.2562,  0.1742, -0.0338, -0.1034, -0.1280, -0.2780